name: Wails Cross Compilation
on:
  push

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: Dockernetes.app
            asset_name: Dockernetes-macos-arm64.app
          - os: windows-latest
            artifact_name: Dockernetes-amd64.exe
            asset_name: ${{ github.event.repository.name }}-windows-amd64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.39
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Wails app
        run: wails build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}