name: Wails build

on:
  push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Dockernetes'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'Dockernetes'
            platform: 'darwin/universal'
            os: 'macos-latest'
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
        shell: bash
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.22'
      - name: Upload builds to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}